name: lapa
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pip=21.2
  - python=3.7
  - pip:
    - cython==0.29.28
    - sphinx==4.4.0
    - sphinx-autoapi==1.8.4
    - sphinx-click==3.1.0
    - sphinx-rtd-theme==1.0.0
    - m2r2==0.3.2
    - nbsphinx==0.8.8